language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - "pip install -r tests/requirements.txt"
  - "python setup.py install"

script:
  - "flake8 tests rocketsled"
  - "py.test tests"
